# apiVersion: v1
# kind: Pod
# metadata: 
#   name: test-pod 
# spec:
#   containers: 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-cnt
    image: nginx:latest