# Pod with environment variables 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  containers:
  - name: nginx-cnt
    image: curlimages/curl
    command: ['sleep' , "600"]  
    ports:
      - containerPort: 80
    env:
      - name: BATCH
        value: "57"
      - name: ENVIRONMENT
        value: "dev" 
      - name: MONGO_URL
        value: "mongodb.cc.com"
      - name: BU 
        value: "payment" 
      - name: MANAGER 
        value: "Steve"

# 1) What if you have multiple environment values to be supplied to the deployment ??? 
# 2) What if you have 8 values that are common ........
# ----  configMap : this is a configMap is a placeHolder to capture all the values and supply it.