# Pod with environment variables 
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  containers:
  - name: nginx-cnt
    image: nginx:latest 
    ports:
      - containerPort: 80
    env:
    - name: BATCH
      value: 57
    - name: ENVIRONMENT
      value: "dev" 
    - MONGO_URL:
      value: "mongodb.cc.com"
    - name: BU 
      value: "payment" 
    - name: MANAGER 
      value: "Steve"