--- 
# Pod with Secrts 
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod 
spec:
  containers:
  - name: nginx-cnt
    image: nginx:latest 
    ports:
      - containerPort: 80
    env: 
      - name: DB_USER
        value: "admin" 
      - name: DB_PWD
        value: "pws-001x"
