### Deployment Set with Recreation Strategy
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 10
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:stable-perl
#         ports:
#         - containerPort: 80 

--- 

### Deployment Set with Recreation Strategy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:              # port where your container listens
        - containerPort: 80 

--- 
# ClusterIP is a service, that is used for inter-service communication and this cannot be accessed from the internet.
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80              # Port where your service listens against
      targetPort: 80        # This is the port where kubernetes service will forward the request to associated pod 